name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type"
        required: true
        default: "normal"
        type: choice
        options:
          - normal
          - canary
          - from-package

permissions:
  contents: write
  id-token: write

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup deps
        uses: ./.github/actions/setup-deps
        with:
          node-version: 24

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "canary" ]; then
            NPM_CONFIG_PROVENANCE=true npm run release-canary -- --yes
          elif [ "${{ github.event.inputs.release_type }}" = "from-package" ]; then
            npx lerna publish from-package --yes
          else
            NPM_CONFIG_PROVENANCE=true npm run release -- --yes
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
